#!/usr/bin/env bash
# Enumerate every uvm_* checker site and require each one to be classified.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

ROSTER=docs/checker_roster.txt
MODE=check
for a in "$@"; do
  case "$a" in
    --regen)   MODE=regen ;;
    --summary) MODE=summary ;;
    --figures) MODE=figures ;;
  esac
done

PROOF_RE='^[A-Za-z0-9_,]+$'          # kept for callers that want the bare shape
NOTPROOF_RE='(INERT|REFUTED|UNPROVEN|VACUOUS)'
KNOWN_SUFFIXES='(INERT|REFUTED|UNPROVEN|VACUOUS|direct|timeout)'
proof_filter () {   # stdin: roster -> stdout: mechanism names with a real proof
  awk -F'|' -v bad="$NOTPROOF_RE" '
    $0 !~ /^#/ && $4=="DESIGN" && $5!="" && $6!="" && $6 !~ bad {print $5}' | sort -u
}
all_mechs () {
  awk -F'|' '$0 !~ /^#/ && $4=="DESIGN" && $5!="" {print $5}' "$ROSTER" | sort -u
}

enumerate () {
  python3 - <<'PY'
import os, re, sys
rows = []
for root, dirs, files in os.walk('tb/uvm'):
    for fn in sorted(files):
        if not fn.endswith(('.sv', '.svh')):
            continue
        p = os.path.join(root, fn)
        L = open(p, errors='replace').read().splitlines()
        for i, raw in enumerate(L):
            line = raw.strip()
            if line.startswith('//'):
                continue
            m = re.search(r'`uvm_(error|fatal|warning)\s*\(', line)
            if not m:
                continue
            sev = m.group(1)
            # the macro's arguments, continued over the next few lines so that a
            # message wrapped onto its own line still yields a fingerprint
            tail = ' '.join(x.strip() for x in L[i:i + 6])
            tail = tail[tail.index(m.group(0)) + len(m.group(0)):]
            qs = re.findall(r'"([^"]*)"', tail)
            cid = qs[0] if qs and re.fullmatch(r'[A-Z_][A-Z_0-9]*', qs[0]) else '?'
            # the fingerprint is the first quoted MESSAGE, i.e. the first quoted
            # string that is not the ID. Keying on the ID alone collapses four
            # cpu_cfg checkers into one row.
            msg = ''
            for q in qs:
                if q == cid or len(q) < 6:
                    continue
                msg = q
                break
            msg = re.sub(r'\s+', ' ', msg).strip()[:42] or '<no literal>'
            rows.append((p, cid, msg, sev, i + 1))
dupes = {}
out = []
for p, cid, msg, sev, ln in rows:
    k = (p, cid, msg)
    dupes[k] = dupes.get(k, 0) + 1
    if dupes[k] > 1:
        # two sites in one file with the same ID and the same opening words: make
        # the key unique rather than silently merging them, which is how a
        # roster under-reports and looks complete.
        msg = f"{msg} #{dupes[k]}"
    out.append(f"{p}|{cid}|{msg}|{sev}|{ln}")
print('\n'.join(out))
PY
}

if [[ $MODE == regen ]]; then
  tmp=$(mktemp)
  {
    echo "# Checker roster. Regenerated by scripts/checker_audit.sh --regen."
    echo "# Every uvm_error / uvm_fatal / uvm_warning site in tb/uvm, with the"
    echo "# class a human assigned it. A new site arrives as '?', and '?' is a"
    echo "# hard failure, so a site cannot enter the environment unclassified."
    echo "#"
    echo "#   STRUCT   testbench wiring: a null interface, a missing config."
    echo "#            No RTL change can provoke one."
    echo "#   VACUOUS  detects ABSENCE. Provable by removing the stimulus."
    echo "#   INSTR    the instrument checking itself."
    echo "#   PROGARG  a bad plusarg or program argument."
    echo "#   REF      the reference model could not step."
    echo "#   DESIGN   a property of the DUT. The mutation-testable target."
    echo "#"
    echo "#   mech     DESIGN rows only: the MECHANISM, because a site is not one."
    echo "#   mut      DESIGN rows only: the mutation that PROVED the mechanism"
    echo "#            can fail. Empty means never shown able to fail, which is"
    echo "#            a hypothesis. See docs/verification.md: a cell counts as"
    echo "#            a proof only if a log contains the checker own words."
    echo "#"
    echo "# file|id|fingerprint|class|mech|mut"
    while IFS='|' read -r f id fp sev ln; do
      old=$(awk -F'|' -v k="$f|$id|$fp" '$0 !~ /^#/ && ($1"|"$2"|"$3)==k {print; exit}' "$ROSTER" 2>/dev/null)
      if [[ -n $old ]]; then echo "$old"; else echo "$f|$id|$fp|?||"; fi
    done < <(enumerate)
  } > "$tmp"
  n=$(grep -vc '^#' "$tmp")
  [[ $n -ge 100 ]] || { echo "!! refusing to write a $n-row roster" >&2; rm -f "$tmp"; exit 1; }
  mv "$tmp" "$ROSTER"
  chmod 644 "$ROSTER"
  echo "$ROSTER regenerated: $n site(s). Classify every '?' by hand."
  exit 0
fi

[[ -f $ROSTER ]] || { echo "no $ROSTER -- run: ./scripts/checker_audit.sh --regen" >&2; exit 1; }

# --figures: `key value` lines and nothing else, for docs_audit.sh to consume.
#
# WHY A MODE AND NOT A COPY. docs_audit.sh derived `proven` with its own awk,
# identical to the one here. Two copies of the rule that decides whether a
# shipped figure is right -- and when the rule changed (a suffixed cell is not a
# proof) it would have changed in one. That is the defect docs_audit.sh exists to
# catch, sitting inside docs_audit.sh. It reads this now.
#
# It deliberately runs BEFORE the mutation guard below: --figures reports what
# the ROSTER says, which is a fact about a checked-in file and is true whether or
# not a mutation is applied to rtl/.
if [[ $MODE == figures ]]; then
  echo "sites $(grep -vc '^#' "$ROSTER")"
  echo "design $(awk -F'|' '$0 !~ /^#/ && $4=="DESIGN" {c++} END{print c+0}' "$ROSTER")"
  echo "mechanisms $(all_mechs | grep -c .)"
  echo "proven $(proof_filter < "$ROSTER" | grep -c .)"
  echo "vacuous $(awk -F'|' '$0 !~ /^#/ && $4=="VACUOUS" {c++} END{print c+0}' "$ROSTER")"
  exit 0
fi

# Same hazard as cite_audit.sh: this reads SOURCE, and a campaign mutates source
# in place. A mutation inside tb/uvm would not happen today (they all target
# rtl/), but the guard is cheap and the assumption is the kind that stops being
# true quietly.
if ls rtl/**/*.mutorig >/dev/null 2>&1 || ls rtl/*/*.mutorig >/dev/null 2>&1; then
  echo "!! A MUTATION IS APPLIED (a .mutorig exists). This audit reads SOURCE;"
  echo "   wait for the campaign to finish before trusting its verdict."
  exit 2
fi

live=$(enumerate)
fail=0

# --- two directions, both failures ---------------------------------------------
missing=""; while IFS='|' read -r f id fp sev ln; do
  grep -qF -- "$f|$id|$fp|" "$ROSTER" || missing="$missing
  $f:$ln  [$id] $fp"
done <<< "$live"

# [REVIEW3] A HERESTRING, NOT A PIPE. THIS AUDIT WAS FLAKY, AND A FLAKY AUDIT IS
# A BATTERY GATE THAT FAILS FOR NO REASON.
#
# WHAT IS MEASURED. The loop below read `echo "$live" | grep -qF ...`. Run 10
# times in a row against an unchanged, correct tree it failed ONCE, reporting a
# roster row as absent from the source -- a row that is plainly there. Two
# earlier back-to-back runs each named a DIFFERENT row, which is what a race
# looks like and what no real staleness ever looks like. With the herestring it
# has now run 16 consecutive times, clean, under the same load.
#
#     piped       1 failure in 10
#     herestring  0 failures in 16
#
# WHAT IS NOT MEASURED, AND IS THEREFORE NOT CLAIMED. The obvious explanation is
# SIGPIPE: `grep -q` exits at the first match, `echo` dies writing the rest, and
# `set -o pipefail` (top of this file) promotes 141 to the pipeline's status. THE
stale=""; while IFS='|' read -r f id fp cls mech; do
  [[ $f == \#* || -z ${f:-} ]] && continue
  grep -qF -- "$f|$id|$fp|" <<< "$live" || stale="$stale
  $f  [$id] $fp"
done < "$ROSTER"

unclass=$(awk -F'|' '$0 !~ /^#/ && $4=="?" {print "  "$1"  ["$2"] "$3}' "$ROSTER")
badsuf=$(awk -F'|' -v ok="$KNOWN_SUFFIXES" '
  $0 !~ /^#/ && $6 ~ /-/ && $6 !~ ok {print "  "$5"  mut="$6}' "$ROSTER" | sort -u)
badrow=$(awk -F'|' '$0 !~ /^#/ && $4!="DESIGN" && $6!="" {print "  "$1"  ["$2"] "$3"  mut="$6}' "$ROSTER")

if [[ -n $missing ]]; then
  echo "!! NOT IN THE ROSTER -- a checker was added and nobody classified it:$missing"; fail=1
fi
if [[ -n $stale ]]; then
  echo "!! IN THE ROSTER AND NOT IN THE SOURCE -- a checker was deleted or reworded:$stale"; fail=1
fi
if [[ -n $unclass ]]; then
  echo "!! UNCLASSIFIED:"; echo "$unclass"; fail=1
fi
if [[ -n $badrow ]]; then
  echo "!! A mut CELL ON A NON-DESIGN ROW. Nothing reads it and nothing checks"
  echo "   it, so it becomes a counted PROOF the moment the row is reclassified."
  echo "   Move the evidence into a comment, or classify the row DESIGN:"
  echo "$badrow"; fail=1
fi
if [[ -n $badsuf ]]; then
  echo "!! UNRECOGNISED mut SUFFIX -- NOTPROOF_RE is a blacklist, so a verdict it"
  echo "   does not know is counted as a PROOF. Add it to NOTPROOF_RE (if it means"
  echo "   not-proven) or to KNOWN_SUFFIXES (if it names a non-mutation experiment):"
  echo "$badsuf"; fail=1
fi

echo
echo "=== uvm_* checker sites, classified ($(echo "$live" | grep -c .) live) ==="
awk -F'|' '$0 !~ /^#/ && NF>=4 { c[$4]++ } END {
  order = "STRUCT VACUOUS INSTR PROGARG REF DESIGN ?"
  n = split(order, o, " ")
  for (i = 1; i <= n; i++) if (o[i] in c) printf "  %-8s %3d\n", o[i], c[o[i]]
}' "$ROSTER"
mech=$(all_mechs | grep -c .)
dsites=$(awk -F'|' '$0 !~ /^#/ && $4=="DESIGN" {c++} END{print c+0}' "$ROSTER")
echo
echo "  $dsites DESIGN site(s) over $mech distinct MECHANISM(s) -- the mutation-testable target."
proven=$(proof_filter < "$ROSTER" | grep -c .)
echo "  $proven of $mech mechanism(s) have been SHOWN ABLE TO FAIL by a mutation."
echo "  The other $((mech-proven)) are hypotheses -- docs/verification.md's own words."
# TRIED-AND-DID-NOT-PROVE IS ITS OWN COLUMN. Folding it into "hypotheses" hides
# the fact that somebody spent a build on it; folding it into "proven" is how
# m14 survived four sessions.
tried=$(awk -F'|' -v bad="$NOTPROOF_RE" '
  $0 !~ /^#/ && $4=="DESIGN" && $5!="" && $6!="" && $6 ~ bad {print $5}' "$ROSTER" | sort -u | grep -c .)
[[ $tried -gt 0 ]] && echo "  Of those, $tried had a mutation RUN against it that did not prove it (suffixed cell)."
if [[ $MODE == summary ]]; then
  echo
  echo "  PROVEN:"
  awk -F'|' -v bad="$NOTPROOF_RE" '$0 !~ /^#/ && $4=="DESIGN" && $6!="" && $6 !~ bad {printf "    %-44s %s\n", $5, $6}' "$ROSTER" | sort -u
  echo
  echo "  NEVER SHOWN ABLE TO FAIL:"
  awk -F'|' -v bad="$NOTPROOF_RE" '$0 !~ /^#/ && $4=="DESIGN" && $5!="" && ($6=="" || $6 ~ bad) {printf "    %-44s %s  %s\n", $5, $1, $6}' "$ROSTER" | sort -u
fi

echo
[[ $fail == 0 ]] && { echo "  CHECKER_AUDIT: pass"; exit 0; }
echo "  CHECKER_AUDIT: FAIL"; exit 1
