#!/usr/bin/env bash
# Every RTL line docs/coverage_proofs.md cites must still be where it says it is.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

DOC=docs/coverage_proofs.md
BEGIN='<!-- BEGIN CITATION ROSTER -- generated by scripts/cite_audit.sh --regen -->'
END='<!-- END CITATION ROSTER -->'
ANCHOR_WIN=6

REGEN=0
DAT=obj_uvm/cov/merged.dat
for a in "$@"; do
  case "$a" in
    --regen)        REGEN=1 ;;
    --anchors-only) DAT="" ;;
    *)              DAT="$a" ;;
  esac
done


[[ -f $DOC ]] || { echo "cite_audit.sh: no $DOC" >&2; exit 1; }

if ls rtl/**/*.mutorig >/dev/null 2>&1 || ls rtl/*/*.mutorig >/dev/null 2>&1; then
  echo "!! A MUTATION IS APPLIED TO THE TREE (a .mutorig exists)."
  echo "   This audit reads SOURCE, so its verdict describes a deliberately"
  echo "   broken design and any DRIFT it reports may be the mutation itself."
  echo "   Wait for scripts/run_mutations.sh to finish, or restore from .mutorig."
  exit 2
fi

resolve () {  # resolve <basename> -> repo-relative path, or empty
  local b=$1 hits
  hits=$(find rtl tb -name "$b" -type f 2>/dev/null)
  [[ $(echo "$hits" | grep -c .) == 1 ]] && { echo "$hits"; return 0; }
  echo ""
}

prose_cites () {
  awk -v b="$BEGIN" -v e="$END" '
    index($0,b) { inblk=1; next }
    index($0,e) { inblk=0; next }
    !inblk     { print }
  ' "$DOC" | grep -oE '[A-Za-z0-9_]+\.sv:[0-9]+' | sort -u
}

if [[ $REGEN == 1 ]]; then
  tmp=$(mktemp); new=$(mktemp)
  {
    echo "$BEGIN"
    echo '```'
    printf '%-34s %-6s %s\n' '# path:line' 'shape' 'anchor (must still be within +/-6 lines)'
    while read -r c; do
      base=${c%%:*}; ln=${c##*:}
      p=$(resolve "$base")
      if [[ -z $p ]]; then
        old=$(awk -v b="$BEGIN" -v e="$END" -v k="$base:$ln" '
          index($0,b){i=1;next} index($0,e){i=0;next}
          i && $1 !~ /^#/ { n=split($1,q,"/"); if (q[n]==k) { print; exit } }' "$DOC")
        if [[ -n $old ]]; then echo "$old"; else
          printf '%-34s %-6s %s\n' "$base:$ln" "?" "<<UNRESOLVED FILE>>"
        fi
        continue
      fi
      txt=$(sed -n "${ln}p" "$p" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | cut -c1-70)
      # KEEP AN EXISTING CLASSIFICATION, matched by ANCHOR first and only then by
      # BASENAME:line. Keying on the line alone would force a re-classification
      # every time anything above a citation moved -- and a roster that churns
      # gets regenerated without being read, which is how a roster stops being a
      # check. This is the same reason docs/checker_roster.txt keys on the
      # message rather than the line. The line-based fallback exists for a
      # hand-disambiguated path (two files are named tb_top.sv).
      old=""
      if [[ -n $txt ]]; then
        old=$(awk -v b="$BEGIN" -v e="$END" -v pp="$p" -v a="$txt" '
          index($0,b){i=1;next} index($0,e){i=0;next}
          i && $1 !~ /^#/ {
            split($1,q,":"); f=$1; sub(/:[0-9]+$/,"",f)
            anc=$0; sub(/^[^ ]+ +[^ ]+ +/,"",anc)
            if (f==pp && anc==a) { print; exit } }' "$DOC")
      fi
      if [[ -z $old ]]; then
        old=$(awk -v b="$BEGIN" -v e="$END" -v k="$base:$ln" '
          index($0,b){i=1;next} index($0,e){i=0;next}
          i && $1 !~ /^#/ { n=split($1,q,"/"); if (q[n]==k) { print; exit } }' "$DOC")
      fi
      if [[ -n $old ]]; then
        # re-emit with the CURRENT line, keeping the shape someone assigned
        sh=$(echo "$old" | awk '{print $2}')
        printf '%-34s %-11s %s\n' "$p:$ln" "$sh" "${txt:-<<EMPTY LINE>>}"
        continue
      fi
      printf '%-34s %-11s %s\n' "$p:$ln" "?" "${txt:-<<EMPTY LINE>>}"
    done < <(prose_cites)
    echo '```'
    echo "$END"
  } > "$new"
  # THE SECOND NET. An audit script that meant to regenerate a block inside this
  # very file once emptied it instead, with no backup on the machine. Verify the
  # replacement before writing, always.
  lines=$(grep -c '' "$new")
  [[ $lines -ge 8 ]] || { echo "!! refusing to write a $lines-line roster" >&2; exit 1; }
  awk -v b="$BEGIN" -v e="$END" -v f="$new" '
    index($0,b) { while ((getline l < f) > 0) print l; skip=1; next }
    index($0,e) { skip=0; next }
    !skip       { print }
  ' "$DOC" > "$tmp"
  grep -c '' "$tmp" | awk -v o="$(grep -c '' "$DOC")" '{ if ($1 < o/2) exit 1 }' \
    || { echo "!! refusing: replacement is less than half the original" >&2; exit 1; }
  mv "$tmp" "$DOC"; rm -f "$new"
  chmod 644 "$DOC"
  echo "roster regenerated in $DOC -- classify every '?' by hand before committing"
  exit 0
fi

# check mode
roster=$(awk -v b="$BEGIN" -v e="$END" '
  index($0,b){i=1;next} index($0,e){i=0;next}
  i && $0 !~ /^```/ && $0 !~ /^#/ && NF {print}' "$DOC")

if [[ -z $roster ]]; then
  echo "!! no citation roster in $DOC. Run: ./scripts/cite_audit.sh --regen" >&2
  exit 1
fi

echo "=== 4d citations vs the RTL they name   ($DOC) ==="
echo

fail=0; n_anchor=0; n_never=0; n_guard=0; n_norec=0; n_hist=0; n_opaque=0; n_unclass=0

# --- half 1: the anchors -------------------------------------------------------
while read -r key shape anchor; do
  [[ -z ${key:-} ]] && continue
  p=${key%:*}; ln=${key##*:}
  if [[ ! -f $p ]]; then
    echo "  DRIFT  $key -- file does not exist"; fail=1; continue
  fi
  if [[ $anchor == '<<'* ]]; then
    echo "  UNCLASSIFIED  $key -- $anchor"; fail=1; n_unclass=$((n_unclass+1)); continue
  fi
  [[ $shape == '?' ]] && { echo "  UNCLASSIFIED  $key -- shape is '?'"; fail=1; n_unclass=$((n_unclass+1)); continue; }
  lo=$((ln-ANCHOR_WIN)); [[ $lo -lt 1 ]] && lo=1; hi=$((ln+ANCHOR_WIN))
  if ! sed -n "${lo},${hi}p" "$p" | grep -qF -- "$anchor"; then
    where=$(grep -nF -- "$anchor" "$p" | head -1 | cut -d: -f1)
    echo "  DRIFT  $key -- anchor not within +/-$ANCHOR_WIN lines${where:+, found at $p:$where}"
    echo "         anchor: $anchor"
    fail=1
  else
    n_anchor=$((n_anchor+1))
  fi
done <<< "$roster"

# --- half 2: the coverage records ----------------------------------------------
if [[ -z $DAT ]]; then
  echo
  echo "  (--anchors-only: the coverage half was not run. cov_sweep.sh runs both.)"
elif [[ ! -f $DAT ]]; then
  echo
  echo "  !! no $DAT -- the coverage half did not run, and this is not a pass."
  echo "     Run ./scripts/cov_sweep.sh, pass a merged .dat, or say --anchors-only."
  fail=1
else
  echo
  echo "=== the two proof shapes, against $DAT ($(date -r "$DAT" '+%Y-%m-%d %H:%M:%S')) ==="
  echo

  # file:line:type:kind -> summed count, for every non-covergroup record.
  recs=$(awk '
    BEGIN { SOH=sprintf("%c",1); STX=sprintf("%c",2) }
    /^#/ { next }
    {
      n=split($0,tok," "); cnt=tok[n]+0
      key=$0; sub(/^C '"'"'/,"",key); sub(/'"'"' *[0-9]+ *$/,"",key)
      delete F; m=split(key,parts,SOH)
      for (i=1;i<=m;i++) { if (parts[i]=="") continue
        j=index(parts[i],STX); if (j==0) continue
        F[substr(parts[i],1,j-1)]=substr(parts[i],j+1) }
      if (F["t"]=="covergroup") next
      k=F["f"] ":" F["l"] ":" F["t"] ":" F["o"]
      s[k]+=cnt
    }
    END { for (k in s) print k, s[k] }' "$DAT")

  while read -r key shape anchor; do
    [[ -z ${key:-} || $shape == '?' ]] && continue
    p=${key%:*}; ln=${key##*:}
    arm=then; base=$shape
    case "$shape" in */else) arm=else; base=${shape%/else} ;; esac
    # +/-1: Verilator records a multi-line expression at its LAST line.
    # EXACT LINE FIRST, then l+1, then l-1 -- never "whichever turns up first".
    # The unordered form picked mesi_ctrl.sv:132 (a different case arm, count 0)
    # over :131 (6,532) and reported the guard unchallenged. An audit that reads
    # the neighbouring construct is worse than no audit: it produces a specific,
    # wrong finding.
    at=""
    for cand in "$ln" "$((ln+1))" "$((ln-1))"; do
      if echo "$recs" | awk -v f="$p" -v l="$cand" -F'[: ]' '$1==f && $2==l {found=1} END{exit !found}'; then
        at=$cand; break
      fi
    done
    hits=""
    [[ -n $at ]] && hits=$(echo "$recs" | awk -v f="$p" -v l="$at" -F'[: ]' \
                             '$1==f && $2==l {printf "%s/%s=%s ", $3,$4,$5}')
    where=""; [[ -n $at && $at != "$ln" ]] && where=" (recorded at :$at)"
    # THEN-arm kinds and ELSE-arm kinds, named rather than inferred.
    if [[ $arm == then ]]; then kinds='if|cond_then|case|elsif|block'
    else                        kinds='else|cond_else'; fi
    sum=$(echo "$recs" | awk -v f="$p" -v l="${at:-0}" -v k="$kinds" -F'[: ]' \
            '$1==f && $2==l && $4 ~ "^("k")$" {c+=$5} END{print c+0}')
    case "$base" in
      never)
        n_never=$((n_never+1))
        if [[ -z $hits ]]; then
          echo "  never  $key -- NO RECORD, so the zero cannot be confirmed"; fail=1
        elif [[ $sum -gt 0 ]]; then
          echo "  never  $key -- the $arm arm EXECUTES ($sum)$where: $hits"; fail=1
        else
          echo "  never  $key  ok   $arm=0$where   $hits"
        fi ;;
      guard)
        n_guard=$((n_guard+1))
        if [[ -z $hits ]]; then
          echo "  guard  $key -- NO RECORD: this instrument cannot say the guard was"
          echo "         ever taken. Re-classify as norec or opaque, or cite the line"
          echo "         that carries the record."; fail=1
        elif [[ $sum -gt 0 ]]; then
          echo "  guard  $key  ok   $arm=$sum$where   $hits"
        else
          echo "  guard  $key -- the $arm arm is NEVER TAKEN$where ($hits). The guard is"
          echo "         unchallenged: this is the m12/m13 class, and it could be"
          echo "         deleted with every gate staying green."; fail=1
        fi ;;
      opaque)
        # A record EXISTS and does not express the condition -- a statement count
        # under an assignment. core.sv:833 runs 1,512 times and that says nothing
        # about whether alu_result[0] was ever 1. Only a PROGRAM settles these,
        # which is what misalign.S and csrprobe.S were extended to do.
        n_opaque=$((n_opaque+1))
        echo "  opaque $key -- statement count only$where ($hits); settled by a program, not by coverage" ;;
      norec)
        n_norec=$((n_norec+1))
        if [[ -n $hits ]]; then
          echo "  norec  $key -- a record APPEARED$where ($hits). Re-classify: it is auditable now."
          fail=1
        fi ;;
      hist)
        n_hist=$((n_hist+1)) ;;
      *)
        echo "  ??     $key -- unknown shape '$shape'"; fail=1 ;;
    esac
  done <<< "$roster"
fi

echo
printf '  %d citation(s): %d anchored | %d never-taken, %d guard, %d opaque, %d not instrumented, %d historical\n' \
  "$(echo "$roster" | grep -c .)" "$n_anchor" "$n_never" "$n_guard" "$n_opaque" "$n_norec" "$n_hist"
[[ $n_unclass -gt 0 ]] && printf '  %d UNCLASSIFIED\n' "$n_unclass"

if [[ $fail == 0 ]]; then
  echo "  CITE_AUDIT: pass"
  exit 0
fi
echo "  CITE_AUDIT: FAIL"
exit 1
