#!/usr/bin/env bash
# Every unhit bin must be accounted for in docs/coverage_proofs.md.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

PROOFS=docs/coverage_proofs.md
BEGIN_MARK='<!-- BEGIN UNHIT ROSTER -- generated by scripts/cov_proof_audit.sh --regen -->'
END_MARK='<!-- END UNHIT ROSTER -->'

REGEN=0
HITONLY=0
DAT=coverage.dat
for a in "$@"; do
  case "$a" in
    --regen)    REGEN=1 ;;
    --hit-only) HITONLY=1 ;;
    *)          DAT="$a" ;;
  esac
done

if [[ ! -f "$DAT" ]]; then
  echo "cov_proof_audit.sh: no $DAT" >&2
  echo "  It is written by the RUN, not the build. Check its timestamp." >&2
  exit 1
fi
[[ -f "$PROOFS" ]] || { echo "cov_proof_audit.sh: no $PROOFS" >&2; exit 1; }

measured=$(awk '
  BEGIN { SOH = sprintf("%c", 1); STX = sprintf("%c", 2) }
  /^#/ { next }
  {
    n = split($0, tok, " "); cnt = tok[n] + 0
    key = $0; sub(/^C '"'"'/, "", key); sub(/'"'"' *[0-9]+ *$/, "", key)
    delete F
    m = split(key, parts, SOH)
    for (i = 1; i <= m; i++) {
      if (parts[i] == "") continue
      p = index(parts[i], STX); if (p == 0) continue
      F[substr(parts[i], 1, p-1)] = substr(parts[i], p+1)
    }
    if (F["t"] != "covergroup") next
    h = F["h"]; sub(/^__vlAnonCG_/, "", h)
    if (cnt == 0) print h
  }' "$DAT" | sort -u)

if [[ $REGEN -eq 1 ]]; then
  grep -qF "$BEGIN_MARK" "$PROOFS" || {
    echo "cov_proof_audit.sh: $PROOFS has no roster block; add the markers first" >&2
    exit 1; }
  lst=$(mktemp); tmp=$(mktemp)
  printf '%s\n' "$measured" > "$lst"
  if ! awk -v b="$BEGIN_MARK" -v e="$END_MARK" -v lf="$lst" '
    $0 == b { print; print "```"; while ((getline ln < lf) > 0) print ln; close(lf);
              print "```"; skip=1; next }
    $0 == e { print; skip=0; next }
    !skip   { print }
  ' "$PROOFS" > "$tmp"; then
    echo "cov_proof_audit.sh: awk failed; $PROOFS untouched" >&2
    rm -f "$tmp" "$lst"; exit 1
  fi
  ok=1
  [[ -s "$tmp" ]] || ok=0
  grep -qF "$BEGIN_MARK" "$tmp" || ok=0
  grep -qF "$END_MARK"   "$tmp" || ok=0
  old_body=$(grep -c '' "$PROOFS")
  new_body=$(grep -c '' "$tmp")
  [[ "$new_body" -ge $(( old_body / 2 )) ]] || ok=0
  if [[ $ok -eq 0 ]]; then
    echo "cov_proof_audit.sh: REFUSING to write -- the regenerated file failed" >&2
    echo "  its sanity check ($new_body lines against $old_body). $PROOFS untouched." >&2
    rm -f "$tmp" "$lst"; exit 1
  fi
  mv "$tmp" "$PROOFS"; rm -f "$lst"
  echo "roster regenerated from $DAT: $(printf '%s\n' "$measured" | grep -c .) unhit bin(s)"
  exit 0
fi

roster=$(awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
  $0 == b { on=1; next } $0 == e { on=0; next }
  on && $0 !~ /^```/ && $0 !~ /^[[:space:]]*$/ { gsub(/^[[:space:]]+|[[:space:]]+$/, ""); print }
' "$PROOFS" | sort -u)

if [[ -z "$roster" ]]; then
  echo "!! $PROOFS carries no roster block. Run --regen once, then review it." >&2
  exit 1
fi

echo "=== unhit bins vs COVERAGE_PROOFS.md   ($DAT, $(date -r "$DAT" '+%Y-%m-%d %H:%M:%S')) ==="
echo

unexplained=$(comm -23 <(echo "$measured") <(echo "$roster"))
stale=$(comm -13 <(echo "$measured") <(echo "$roster"))
if [[ $HITONLY -eq 1 ]]; then unexplained=""; fi

n_m=$(echo "$measured" | grep -c . || true)
n_u=$(echo "$unexplained" | grep -c . || true)
n_s=$(echo "$stale" | grep -c . || true)

if [[ $HITONLY -eq 1 ]]; then
  printf "  hit-only mode: %d roster entr(ies) checked against %d unhit bin(s)\n" \
         "$(printf '%s\n' "$roster" | grep -c .)" "$n_m"
else
  printf "  %4d bin(s) unhit and accounted for\n" $(( n_m - n_u ))
fi

if [[ $n_u -gt 0 ]]; then
  echo
  echo "!! $n_u UNHIT BIN(S) WITH NO ENTRY IN $PROOFS:"
  echo "$unexplained" | sed 's/^/     /'
  echo "   Each needs a proof, a program, or an explicit statement that it has"
  echo "   neither. What it must never get is silence."
fi

if [[ $n_s -gt 0 ]]; then
  echo
  echo "!! $n_s ROSTER ENTR(IES) THAT ARE NOW HIT:"
  echo "$stale" | sed 's/^/     /'
  echo "   Either a program closed it -- in which case the proof is stale and the"
  echo "   roster must be regenerated -- or the design just falsified a claim this"
  echo "   file makes about it. Read the section before regenerating."
fi

echo
if [[ $n_u -eq 0 && $n_s -eq 0 ]]; then
  if [[ $HITONLY -eq 1 ]]; then
    echo "    0 roster entr(ies) hit."
  else
    echo "    0 unexplained unhit bin(s), 0 stale roster entr(ies)."
  fi
  exit 0
fi
exit 1
