#!/usr/bin/env python3
"""Constrained-random program generator for this platform: multi-hart, with a
sharing rate so the two harts contend for the same lines. Termination is
structural (counted loop trips), never probabilistic, because a hang is
indistinguishable from a dozen real defects."""
import argparse, random, sys, os

# Caller-saved only. s-registers are callee-saved and `main` returns with `ret`,
# so writing them would corrupt crt0's frame; a0 is the return value; sp/gp/tp/ra
# belong to the runtime. t0 and t1 are reserved below.
POOL = ["t2","t3","t4","t5","t6","a1","a2","a3","a4","a5","a6","a7"]
BASE = "t0"     # buffer base for this hart
CTR  = "t1"     # loop counter, never written by a loop body

RR  = ["add","sub","sll","slt","sltu","xor","srl","sra","or","and"]
RI  = ["addi","slti","sltiu","xori","ori","andi"]
SH  = ["slli","srli","srai"]
MUL = ["mul","mulh","mulhsu","mulhu","div","divu","rem","remu"]
BR  = ["beq","bne","blt","bge","bltu","bgeu"]
LD  = [("lw",4),("lh",2),("lhu",2),("lb",1),("lbu",1)]
ST  = [("sw",4),("sh",2),("sb",1)]


class Gen:
    def __init__(self, a):
        self.a = a
        self.r = random.Random(a.seed)
        self.n = 0
        self.lbl = 0

    def reg(self):   return self.r.choice(POOL)
    def imm(self):   return self.r.randint(-2048, 2047)
    def shamt(self): return self.r.randint(0, 31)

    def newlbl(self, p="L"):
        self.lbl += 1
        return f".{p}{self.lbl}_{self.a.seed}"

    def addr(self):
        """An ALIGNED offset inside this hart's slice, or the shared slice."""
        shared = self.r.random() < self.a.shared_rate
        # SLICE_WORDS words per hart; the shared slice sits at index 0 and each
        # hart's private slice starts after it.
        if shared:
            off = self.r.randrange(0, self.a.shared_words) * 4
            return off, True
        off = self.a.shared_words * 4 + self.r.randrange(0, self.a.slice_words) * 4
        return off, False

    def mem_op(self, out):
        off, shared = self.addr()
        if self.r.random() < self.a.store_rate:
            op, w = self.r.choice(ST)
        else:
            op, w = self.r.choice(LD)
        # keep the ACCESS aligned to its own width, not just to 4
        off += self.r.randrange(0, 4 // w) * w
        tag = "  # shared" if shared else ""
        if op.startswith("s"):
            out.append(f"  {op:<6} {self.reg()}, {off}({BASE}){tag}")
        else:
            out.append(f"  {op:<6} {self.reg()}, {off}({BASE}){tag}")
        self.n += 1

    def alu(self, out):
        k = self.r.random()
        if k < self.a.mul_rate:
            out.append(f"  {self.r.choice(MUL):<6} {self.reg()}, {self.reg()}, {self.reg()}")
        elif k < self.a.mul_rate + 0.35:
            out.append(f"  {self.r.choice(RR):<6} {self.reg()}, {self.reg()}, {self.reg()}")
        elif k < self.a.mul_rate + 0.60:
            out.append(f"  {self.r.choice(RI):<6} {self.reg()}, {self.reg()}, {self.imm()}")
        elif k < self.a.mul_rate + 0.75:
            out.append(f"  {self.r.choice(SH):<6} {self.reg()}, {self.reg()}, {self.shamt()}")
        else:
            out.append(f"  lui    {self.reg()}, {self.r.randrange(0, 1 << 20)}")
        self.n += 1

    def branch(self, out):
        """FORWARD ONLY. The skipped body is real work, so both directions retire."""
        l = self.newlbl("F")
        out.append(f"  {self.r.choice(BR):<6} {self.reg()}, {self.reg()}, {l}")
        for _ in range(self.r.randint(1, self.a.branch_body)):
            self.alu(out)
        out.append(f"{l}:")
        self.n += 1

    def loop(self, out):
        """The ONLY backward branch shape, and it is counted."""
        l = self.newlbl("LOOP")
        trips = self.r.randint(2, self.a.loop_trips)
        out.append(f"  li     {CTR}, {trips}")
        out.append(f"{l}:")
        for _ in range(self.r.randint(2, self.a.loop_body)):
            if self.r.random() < self.a.mem_rate: self.mem_op(out)
            else:                                 self.alu(out)
        out.append(f"  addi   {CTR}, {CTR}, -1")
        out.append(f"  bnez   {CTR}, {l}")
        self.n += 2

    def body(self):
        out = []
        while self.n < self.a.length:
            k = self.r.random()
            if   k < self.a.loop_rate:                        self.loop(out)
            elif k < self.a.loop_rate + self.a.branch_rate:   self.branch(out)
            elif k < self.a.loop_rate + self.a.branch_rate + self.a.mem_rate:
                self.mem_op(out)
            else:                                             self.alu(out)
        return out

    def emit(self):
        a = self.a
        L = []
        L.append("# " + "=" * 75)
        L.append(f"# rand_{a.seed}.S -- GENERATED by scripts/gen_random_prog.py. Do not edit.")
        L.append("#")
        L.append("# Regenerate exactly:")
        L.append(f"#   ./scripts/gen_random_prog.py --seed {a.seed} --length {a.length} \\")
        L.append(f"#       --mem-rate {a.mem_rate} --branch-rate {a.branch_rate} \\")
        L.append(f"#       --loop-rate {a.loop_rate} --mul-rate {a.mul_rate} \\")
        L.append(f"#       --store-rate {a.store_rate} --shared-rate {a.shared_rate}")
        L.append("#")
        L.append("# The ORACLE is Spike, through sb_retire -- `main` returns 0 and carries no")
        L.append("# verdict of its own. Every branch is forward; the only backward branch is the")
        L.append("# counted loop shape, so this program terminates by construction.")
        L.append("# " + "=" * 75)
        L.append("")
        L.append("  .section .text")
        L.append("  .globl main")
        L.append("main:")
        L.append("  # Per-hart base. Each hart owns its own slice, so by default the two")
        L.append("  # streams do not race and the reference comparison is deterministic.")
        L.append(f"  la     {BASE}, rbuf")
        L.append("  csrr   t2, mhartid")
        L.append(f"  li     t3, {a.slice_words * 4}")
        L.append("  mul    t2, t2, t3")
        L.append(f"  add    {BASE}, {BASE}, t2")
        L.append("")
        L += self.body()
        L.append("")
        L.append("  li     a0, 0")
        L.append("  ret")
        L.append("")
        L.append("  .section .data")
        L.append("  .align 4")
        L.append("rbuf:")
        total = a.shared_words + a.slice_words * a.harts
        for i in range(total):
            L.append(f"  .word 0x{(0x1000_0000 + i * 0x0101_0101) & 0xFFFFFFFF:08x}")
        return "\n".join(L) + "\n"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--seed", type=int, required=True)
    p.add_argument("--length", type=int, default=400)
    p.add_argument("--out", default=None)
    p.add_argument("--harts", type=int, default=2)
    # ---- THE CONSTRAINTS. These are the knobs the closure loop turns. --------
    p.add_argument("--mem-rate",    type=float, default=0.30)
    p.add_argument("--branch-rate", type=float, default=0.12)
    p.add_argument("--loop-rate",   type=float, default=0.05)
    p.add_argument("--mul-rate",    type=float, default=0.10)
    p.add_argument("--store-rate",  type=float, default=0.45)
    p.add_argument("--shared-rate", type=float, default=0.00)
    p.add_argument("--branch-body", type=int,   default=4)
    p.add_argument("--loop-body",   type=int,   default=6)
    p.add_argument("--loop-trips",  type=int,   default=8)
    p.add_argument("--slice-words", type=int,   default=192)
    p.add_argument("--shared-words",type=int,   default=16)
    a = p.parse_args()
    if a.shared_rate > 0 and a.shared_words == 0:
        sys.exit("--shared-rate > 0 needs --shared-words > 0")
    txt = Gen(a).emit()
    if a.out:
        os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
        open(a.out, "w").write(txt)
        print(a.out)
    else:
        sys.stdout.write(txt)

main()
